name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to FastPanel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FASTPANEL_HOST }}
        username: ${{ secrets.FASTPANEL_USER }}
        port: ${{ secrets.FASTPANEL_PORT }}
        key: ${{ secrets.FASTPANEL_SSH_KEY }}
        script: |
          cd /var/www/fastuser/data/www/infissi.omoxsoft.com.ua
          
          # Stop PM2
          pm2 stop punto-infissi-crm || true
          
          # Update from Git
          git pull origin main
          
          # Install dependencies
          npm ci --production
          
          # Create next.config.js
          cat > next.config.js << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            typescript: {
              ignoreBuildErrors: true,
            },
            eslint: {
              ignoreDuringBuilds: true,
            },
          };
          module.exports = nextConfig;
          EOF
          
          # Build project
          npm run build
          
          # Start PM2
          pm2 start punto-infissi-crm
          
          echo "Deploy completed successfully!"