module.exports = {
  apps: [{
    name: 'punto-infissi-crm',
    script: 'npm',
    args: 'start',
    cwd: '/var/www/punto-infissi-crm',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',
    env: {
      NODE_ENV: 'production',
      PORT: 3000
    },
    env_production: {
      NODE_ENV: 'production',
      PORT: 3000
    },
    error_file: '/var/log/pm2/punto-infissi-crm-error.log',
    out_file: '/var/log/pm2/punto-infissi-crm-out.log',
    log_file: '/var/log/pm2/punto-infissi-crm.log',
    time: true
  }]
}


