name: Deploy to FastPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint --if-present
      
    - name: Build project
      run: npm run build
      
    - name: Create deployment archive
      run: |
        tar -czf punto-infissi-crm.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=.next/cache \
          --exclude=*.log \
          .
          
    - name: Deploy to FastPanel
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FASTPANEL_HOST }}
        username: ${{ secrets.FASTPANEL_USER }}
        port: ${{ secrets.FASTPANEL_PORT }}
        key: ${{ secrets.FASTPANEL_SSH_KEY }}
        script: |
          cd /var/www/fastuser/data/www/infissi.omoxsoft.com.ua
          
          # Backup current version
          if [ -d "backup" ]; then
            rm -rf backup
          fi
          mkdir -p backup
          cp -r . backup/ 2>/dev/null || true
          
          # Stop PM2 process
          pm2 stop punto-infissi-crm || true
          
          # Clean directory
          find . -maxdepth 1 -not -name 'backup' -not -name '.' -exec rm -rf {} \;
          
    - name: Upload files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FASTPANEL_HOST }}
        username: ${{ secrets.FASTPANEL_USER }}
        port: ${{ secrets.FASTPANEL_PORT }}
        key: ${{ secrets.FASTPANEL_SSH_KEY }}
        source: "punto-infissi-crm.tar.gz"
        target: "/var/www/fastuser/data/www/infissi.omoxsoft.com.ua/"
        
    - name: Extract and setup
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FASTPANEL_HOST }}
        username: ${{ secrets.FASTPANEL_USER }}
        port: ${{ secrets.FASTPANEL_PORT }}
        key: ${{ secrets.FASTPANEL_SSH_KEY }}
        script: |
          cd /var/www/fastuser/data/www/infissi.omoxsoft.com.ua
          
          # Extract archive
          tar -xzf punto-infissi-crm.tar.gz
          rm punto-infissi-crm.tar.gz
          
          # Install dependencies
          npm ci --production
          
          # Run Prisma migrations
          npx prisma migrate deploy
          npx prisma generate
          
          # Create next.config.js for build
          cat > next.config.js << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            typescript: {
              ignoreBuildErrors: true,
            },
            eslint: {
              ignoreDuringBuilds: true,
            },
          };
          module.exports = nextConfig;
          EOF
          
          # Build project
          npm run build
          
          # Start with PM2
          pm2 start punto-infissi-crm
          
          # Check status
          pm2 status